# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pipx install ruff
    - name: Test with pytest
      run: |
        pytest tests --ignore-glob='**/__init__.py'
    - name: Lint code with Ruff
      run: ruff check --output-format=github --target-version=py39
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py39
      continue-on-error: true
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token provided automatically by GitHub Actions
      with:
        tag_name: ${{ github.ref_name }} # Tag name for the release
        release_name: Release ${{ github.ref_name }} # Name of the release
        body: |
          Changes in this Release:
          - First Change
          - Second Change
        draft: false
        prerelease: false
